// Logbook template for N720AK maintenance records
// Generates professional printable logbook pages from TSV data
//
// Usage: This file is generated by scripts/build_logbooks.py
// which fills in the parameters and entry data below.

#let logbook(
  aircraft-type: "RV-10",
  n-number: "N720AK",
  serial-number: "41649",
  builder: "Samuel E. Ritchie",
  logbook-type: "Airframe",
  generated-date: "",
  data-page-content: [],
  entries: (),
) = {
  set document(title: [#n-number #logbook-type Maintenance Log], author: n-number)

  set page(
    paper: "us-letter",
    flipped: true,
    margin: (top: 0.6in, bottom: 0.7in, left: 0.75in, right: 0.75in),
    header: context {
      if counter(page).get().first() > 2 {
        set text(size: 8pt, fill: rgb("#555"))
        [#logbook-type Maintenance Log #h(1fr) #n-number — #aircraft-type (S/N #serial-number) #h(1fr) Page #counter(page).display()]
        line(length: 100%, stroke: 0.4pt + rgb("#999"))
      }
    },
    footer: context {
      if counter(page).get().first() > 2 {
        line(length: 100%, stroke: 0.4pt + rgb("#999"))
        v(2pt)
        set text(size: 7pt, fill: rgb("#777"))
        [Generated #generated-date from digital maintenance records maintained per 14 CFR 91.417 #h(1fr) github.com/sritchie/rv10]
      }
    },
  )

  set text(font: "New Computer Modern", size: 9pt)

  // ===== TITLE PAGE =====
  {
    set page(header: none, footer: none)
    v(1.5in)
    align(center)[
      #text(size: 12pt, fill: rgb("#555"), tracking: 0.15em, weight: "regular")[AIRCRAFT MAINTENANCE RECORD]
      #v(0.4in)
      #text(size: 36pt, weight: "bold")[#n-number]
      #v(0.15in)
      #text(size: 18pt, fill: rgb("#333"))[#logbook-type Log]
      #v(0.5in)
      #line(length: 40%, stroke: 0.8pt + rgb("#999"))
      #v(0.5in)
      #text(size: 13pt)[
        Van's #aircraft-type \
        Serial Number #serial-number
      ]
      #v(0.3in)
      #text(size: 11pt, fill: rgb("#555"))[
        Builder: #builder
      ]
      #v(1.5in)
      #text(size: 9pt, fill: rgb("#888"))[
        This logbook is generated from digital maintenance records \
        maintained in accordance with 14 CFR 91.417. \
        #v(0.1in)
        Generated #generated-date
      ]
    ]
    pagebreak()
  }

  // ===== DATA PAGE =====
  {
    set page(header: none, footer: none)
    data-page-content
    pagebreak()
  }

  // ===== ENTRY PAGES =====
  {
    // Table header style
    let header-cell(content) = table.cell(
      fill: rgb("#2c3e50"),
      text(fill: white, weight: "bold", size: 8pt, content),
    )

    let row-color(i) = if calc.rem(i, 2) == 0 { rgb("#f8f9fa") } else { white }

    // Render entries in a table
    // Each entry is a dictionary with: date, tach, hobbs, work_type, description, parts, performed_by
    if entries.len() == 0 {
      align(center)[
        #v(2in)
        #text(size: 14pt, fill: rgb("#999"))[No entries recorded.]
      ]
    } else {
      table(
        columns: (0.8in, 0.5in, 0.5in, 0.7in, 1fr, 1.5in, 1.3in),
        align: (left, right, right, left, left, left, left),
        stroke: 0.4pt + rgb("#ddd"),
        inset: (x: 4pt, y: 5pt),

        // Header row
        header-cell[Date],
        header-cell[Tach],
        header-cell[Hobbs],
        header-cell[Type],
        header-cell[Description of Work Performed],
        header-cell[Parts Used],
        header-cell[Performed By],

        // Data rows
        ..entries.enumerate().map(((i, entry)) => {
          let bg = row-color(i)
          (
            table.cell(fill: bg, text(size: 8pt, weight: "bold", entry.date)),
            table.cell(fill: bg, text(size: 8pt, entry.tach)),
            table.cell(fill: bg, text(size: 8pt, entry.hobbs)),
            table.cell(fill: bg, text(size: 7.5pt, style: "italic", entry.work_type)),
            table.cell(fill: bg)[
              #text(size: 8pt, entry.description)
              #if entry.notes != "" {
                v(2pt)
                text(size: 7pt, fill: rgb("#666"), style: "italic")[Note: #entry.notes]
              }
              #if entry.next_due != "" {
                v(1pt)
                text(size: 7pt, fill: rgb("#c0392b"), weight: "bold")[Next due: #entry.next_due]
              }
            ],
            table.cell(fill: bg, text(size: 7.5pt, entry.parts)),
            table.cell(fill: bg, text(size: 7.5pt, entry.performed_by)),
          )
        }).flatten(),
      )

      v(0.4in)

      // Signature block
      block(
        width: 100%,
        stroke: 0.5pt + rgb("#ccc"),
        inset: 12pt,
        radius: 3pt,
      )[
        #text(size: 8pt)[
          I certify that the entries on this page are true and correct. These entries were originally recorded in digital maintenance logs maintained per 14 CFR 91.417.
        ]
        #v(0.25in)
        #grid(
          columns: (1fr, 1fr, 1fr),
          column-gutter: 0.5in,
          [
            #line(length: 100%, stroke: 0.5pt)
            #text(size: 7pt)[Signature]
          ],
          [
            #line(length: 100%, stroke: 0.5pt)
            #text(size: 7pt)[Date]
          ],
          [
            #line(length: 100%, stroke: 0.5pt)
            #text(size: 7pt)[Certificate Number]
          ],
        )
      ]
    }
  }
}
