#!/usr/bin/env python3
"""
Turn every open wiring question into a condition-inspection checklist.

The wire lists carry two kinds of doubt:

  * rows flagged `review` -- the drawing could not settle them, or they are
    known but not yet drawn
  * recorded changes the owner described from memory ("unverified",
    "best recollection")
  * drawn wires whose notes say "Confirm at inspection:" -- the record gives
    the connection, but something about it does not add up

Rather than chase each one separately, they are settled in one pass with the
panels open at the condition inspection. This script writes them to
`wiring/INSPECT.md`, grouped by system, each with what to look at. Because it
is generated from the wire lists it cannot drift: answer an item, record it in
`wiring/changes.tsv` (or fix the extractor), regenerate, and it drops off.

  uv run python3 scripts/wirelist_inspect.py
"""

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import wirelist_changes  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
TITLES = {"PWR": "Power & Lighting", "SV": "SkyView, audio and grips", "O2": "Oxygen",
          "ONSPEED": "OnSpeed", "EMS": "Engine monitoring",
          "WING": "Wings, tailcone and under-seat terminal blocks"}
ORDER = ("PWR", "SV", "ONSPEED", "O2", "WING", "EMS")
CONFIRM = "Confirm at inspection:"
DOUBT = ("unverified", "best recollection")
# Work that needs the drawings, not the airplane. Kept off the hangar list.
DESK_WORK = ("not yet extracted", "replaced when")


def where(r):
    a = f'{r["from_ref"]}{":" + r["from_pin"] if r["from_pin"] else ""}'
    b = f'{r["to_ref"]}{":" + r["to_pin"] if r["to_pin"] else ""}'
    return a if not r["to_ref"] else f"{a} → {b}"


def main():
    # sheet -> question -> (kind, [wires], context). One question can cover
    # many wires (every lead in a bundle whose colour code is unrecorded);
    # it is one thing to look at, so it is one item.
    items = {}

    def add(sheet, kind, question, wire, context=""):
        q = items.setdefault(sheet, {}).setdefault(question, [kind, [], context])
        if wire not in q[1]:
            q[1].append(wire)

    for sheet in wirelist_changes.sheets():
        for r in wirelist_changes.as_built(sheet):
            if r["review"] and not any(d in r["review"] for d in DESK_WORK):
                add(sheet, "check", r["review"], where(r), "" if r["review"] in r["notes"] else r["notes"])
            elif CONFIRM in r["notes"]:
                add(sheet, "confirm", r["notes"].split(CONFIRM, 1)[1].split("  |  ")[0].strip(), where(r))
    for c in wirelist_changes.changes():
        if any(d in c["notes"].lower() for d in DOUBT):
            r = dict(from_ref=c["ref"], from_pin=c["pin"], to_ref=c["to_ref"], to_pin=c["to_pin"])
            add(c["sheet"], "confirm", "recorded from memory - confirm it is wired this way", where(r),
                f'{c["id"]}: {c["notes"]}')

    n = sum(len(v) for v in items.values())
    out = ["# Wiring — Condition Inspection Checklist", "",
           "*Generated by `scripts/wirelist_inspect.py` from the wire lists. Do not edit by hand:",
           "settle an item, tell Claude, and it is recorded in `wiring/changes.tsv` (or the handbook",
           "table the wire list is read from) and drops off this list on the next regeneration.*", "",
           f"**{n} items.** Each is something the drawings and build notes could not settle, a",
           "connection that is recorded but does not add up, or a change recorded from memory.",
           "Settle them with the panels open.", ""]
    order = [s for s in ORDER if s in items] + [s for s in items if s not in ORDER]
    for sheet in order:
        out += [f"## {TITLES.get(sheet, sheet)}", ""]
        for question, (kind, wires, note) in items[sheet].items():
            if len(wires) == 1:
                out.append(f"- [ ] **{wires[0]}** — {question}")
            else:
                out.append(f"- [ ] {question[0].upper() + question[1:]}")
                out.append(f"      <br>*Wires: {'; '.join(wires)}*")
            if note:
                out.append(f"      <br>*{note}*")
        out.append("")
    (REPO / "wiring" / "INSPECT.md").write_text("\n".join(out))
    print(f"wiring/INSPECT.md: {n} items")
    return 0


if __name__ == "__main__":
    sys.exit(main())
