#!/usr/bin/env python3
"""
Turn every open wiring question into a condition-inspection checklist.

The wire lists carry two kinds of doubt:

  * rows flagged `review` -- the drawing could not settle them, or they are
    known but not yet drawn
  * recorded changes the owner described from memory ("unverified",
    "best recollection")

Rather than chase each one separately, they are settled in one pass with the
panels open at the condition inspection. This script writes them to
`wiring/INSPECT.md`, grouped by system, each with what to look at. Because it
is generated from the wire lists it cannot drift: answer an item, record it in
`wiring/changes.tsv` (or fix the extractor), regenerate, and it drops off.

  uv run python3 scripts/wirelist_inspect.py
"""

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import wirelist_changes  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
TITLES = {"PWR": "Power & Lighting", "SV": "SkyView, audio and grips", "O2": "Oxygen",
          "ONSPEED": "OnSpeed", "EMS": "Engine monitoring"}
DOUBT = ("unverified", "best recollection")
# Work that needs the drawings, not the airplane. Kept off the hangar list.
DESK_WORK = ("not yet extracted", "replaced when")


def where(r):
    a = f'{r["from_ref"]}{":" + r["from_pin"] if r["from_pin"] else ""}'
    b = f'{r["to_ref"]}{":" + r["to_pin"] if r["to_pin"] else ""}'
    return a if not r["to_ref"] else f"{a} → {b}"


def main():
    items = {}
    for sheet in wirelist_changes.sheets():
        for r in wirelist_changes.as_built(sheet):
            if r["review"] and not any(d in r["review"] for d in DESK_WORK):
                items.setdefault(sheet, []).append(("check", where(r), r["review"], r["notes"]))
    for c in wirelist_changes.changes():
        if any(d in c["notes"].lower() for d in DOUBT):
            r = dict(from_ref=c["ref"], from_pin=c["pin"], to_ref=c["to_ref"], to_pin=c["to_pin"])
            items.setdefault(c["sheet"], []).append(
                ("confirm", where(r), "recorded from memory - confirm it is wired this way", f'{c["id"]}: {c["notes"]}'))

    n = sum(len(v) for v in items.values())
    out = ["# Wiring — Condition Inspection Checklist", "",
           "*Generated by `scripts/wirelist_inspect.py` from the wire lists. Do not edit by hand:",
           "settle an item, tell Claude, and it is recorded in `wiring/changes.tsv` and drops off",
           "this list on the next regeneration.*", "",
           f"**{n} items.** Each is something the 2017 SteinAir drawings could not settle, or a change",
           "recorded from memory. Settle them with the panels open.", ""]
    order = [s for s in ("PWR", "SV", "ONSPEED", "O2", "EMS") if s in items] + \
            [s for s in items if s not in ("PWR", "SV", "ONSPEED", "O2", "EMS")]
    for sheet in order:
        out += [f"## {TITLES.get(sheet, sheet)}", ""]
        for kind, w, what, note in items[sheet]:
            out.append(f"- [ ] **{w}** — {what}")
            if note:
                out.append(f"      <br>*{note}*")
        out.append("")
    (REPO / "wiring" / "INSPECT.md").write_text("\n".join(out))
    print(f"wiring/INSPECT.md: {n} items")
    return 0


if __name__ == "__main__":
    sys.exit(main())
